name: snake
on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [main]
  schedule:
    - cron: "0 16 * * *"
jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Generate grid snake animations
        uses: Platane/snk@v3.0.0
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/grid-snake.svg
            dist/grid-snake-dark.svg?palette=github-dark
            dist/grid-snake-light.svg?palette=github-light
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload animations as an artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          name: animation
          path: dist/

      - name: Push animations to output branch
        if: github.event_name != 'pull_request'
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
          keep_history: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
